# Generated by Django 6.0.1 on 2026-01-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='team_name',
            field=models.CharField(default='Unknown Team', max_length=100),
        ),
        migrations.AddField(
            model_name='participant',
            name='teammates_names',
            field=models.TextField(blank=True, help_text='Comma-separated list of teammates'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='license_number',
            field=models.CharField(help_text="Captain's Summoner Name (e.g. Faker#KR1)", max_length=50),
        ),
        migrations.AlterField(
            model_name='participant',
            name='ranking_points',
            field=models.IntegerField(default=0, help_text='Team Average MMR/LP'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='discipline',
            field=models.CharField(choices=[('5v5_summoners_rift', '5v5 Summoners Rift'), ('1v1_howling_abyss', '1v1 Howling Abyss')], max_length=50),
        ),
    ]
