# Generated by Django 6.0.1 on 2026-01-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_match_player1_vote_match_player2_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='location_url',
            field=models.URLField(help_text='Google Maps Embed URL', max_length=1000),
        ),
    ]
