# Generated by Django 6.0.1 on 2026-01-15 16:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_alter_tournament_location_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('tournament', 'user')},
        ),
        migrations.AlterField(
            model_name='participant',
            name='license_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='participant',
            name='ranking_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='participant',
            name='team_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='participant',
            name='teammates_names',
            field=models.TextField(blank=True, help_text='Comma-separated names'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='deadline',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='discipline',
            field=models.CharField(choices=[('5v5_summoners_rift', "5v5 Summoner's Rift"), ('1v1_howling_abyss', '1v1 Howling Abyss')], default='5v5_summoners_rift', max_length=50),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='location_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='max_participants',
            field=models.IntegerField(default=16),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('ongoing', 'Ongoing'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='open', max_length=20),
        ),
    ]
