# Generated by Django 6.0.1 on 2026-01-15 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_sponsor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['round_number', 'match_number']},
        ),
    ]
